In [1]:
from skrebate import ReliefF
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime
%matplotlib inline

In [2]:
df=pd.read_csv('SNP.1000.Sample.500.Genotype.epiq',delimiter='\t')
x1=df.drop('HeaderLine',axis=1).transpose()
X=x1.to_numpy()

In [3]:
df2=pd.read_csv('./2_Add_QTN1_Epi_QTN_h.2_0.99_add.eff_0.95_epis.eff_0.95_reps_100/Simulated.Data.100.Reps.Herit.0.99.txt',delimiter='\t')

In [4]:
Y=df2.drop('HeaderLine',axis=1).to_numpy()

In [5]:
Y[0].shape

(500,)

In [6]:
X.shape

(500, 1000)

In [7]:
add0=set([156,615])
epi0=set([420,583])

In [8]:
def findSNP(X,y,add0,epi0):
    fs=ReliefF()
    fs.fit(X,y)
    l0=fs.feature_importances_
    #sel=abs(l0)>0
    sel=abs(l0)>np.mean(abs(l0))
    coefs=set(np.arange(len(l0))[sel])
    
    res={}
    
    tp_add=len(coefs & add0)
    tp_epi=len(coefs & epi0)
    
    fp = len(coefs) - tp_add - tp_epi

    
    res['tpr_add']=tp_add/len(add0)
    res['tpr_epi']=tp_epi/len(epi0)
    res['fpr']=fp/len(coefs)
    
    
    return res

In [9]:
t0=datetime.datetime.now()
stat={'tpr_add':0,'tpr_epi':0,'fpr':0}
for ii in range(len(Y)):
    res=findSNP(X,Y[ii],add0,epi0)
    stat['tpr_add']+=res['tpr_add']
    stat['tpr_epi']+=res['tpr_epi']
    stat['fpr']+=res['fpr']
    
stat['tpr_add']=stat['tpr_add']/len(Y)
stat['tpr_epi']=stat['tpr_epi']/len(Y)
stat['fpr']=stat['fpr']/len(Y)
t1=datetime.datetime.now()
print(stat)
print(t1-t0)

{'tpr_add': 1.0, 'tpr_epi': 0.0, 'fpr': 0.9949238578680201}
3:36:40.432057


In [46]:
l0=fs.feature_importances_

In [47]:
idx=np.array(range(1000))

In [54]:
idx[l0>0.07]

array([105, 235, 278, 408, 434, 590, 708, 780])

In [51]:
df.transpose().columns[278]

278

In [68]:
dfL0=pd.DataFrame(abs(l0))

In [69]:
dfL0.describe()

0
count  1000.000000
mean      0.018248
std       0.024108
min       0.000001
25%       0.006332
50%       0.013954
75%       0.024869
max       0.526493

In [70]:
idx[l0>0.08]

array([105, 278, 434, 590])

In [72]:
l0[[105,278,434,590]]

array([0.08157547, 0.52649308, 0.35395357, 0.08894923])